/**
 * Mock search results for "/search" — modeled on the live Homans / Peirce
 * search response for `q=blower motor`. Enough real-shaped rows (24 by default
 * to match the source page's default page_size) so the results grid, facets,
 * and pagination all render with realistic counts.
 *
 * When the registry-driven PDPs land search integration, this file goes away
 * and results come from `/pdp/_lib/registry` (or a real search endpoint).
 */

export type SearchResult = {
  id: string;
  title: string;
  brand: string;
  item: string;
  mfg: string;
  image?: string;
  /** Rendered when signed-in. Signed-out shows the gated "Sign in to view" copy. */
  price?: number;
  points?: number;
  stockStatus?: "in-stock" | "low-stock" | "out-of-stock";
  /** All-branches stock count (rendered in the "All Branches" facet). */
  allBranchesQty?: number;
  /** Facet index — the sidebar counts derive from these. */
  amps?: string;
  basisOfRotationView?: "Drive End" | "Lead End" | "Shaft End";
  bearingType?: "Ball" | "Self Aligning (SAB)" | "Sleeve";
  capacitorMfdF?: string;
};

export const MOCK_RESULTS: SearchResult[] = [
  {
    id: "58MV660006",
    title: "Factory Authorized Parts™ - Blower Motor 1/2 HP - 120/240 V - 7.7/4.3 Amp - 1050 RPM",
    brand: "Factory Authorized Parts",
    item: "58MV660006",
    mfg: "58MV 660 006",
    price: 328.75,
    points: 328,
    stockStatus: "in-stock",
    allBranchesQty: 12,
    amps: "7.7",
    basisOfRotationView: "Lead End",
    bearingType: "Ball",
    capacitorMfdF: "7.5",
  },
  {
    id: "58MV660004",
    title: "Factory Authorized Parts™ - Blower Motor 1/2 HP - 120/240 V - 7.7/4.3 Amp - 1300 RPM",
    brand: "Factory Authorized Parts",
    item: "58MV660004",
    mfg: "58MV 660 004",
    price: 342.10,
    points: 342,
    stockStatus: "in-stock",
    allBranchesQty: 8,
    amps: "7.7",
    basisOfRotationView: "Lead End",
    bearingType: "Ball",
    capacitorMfdF: "7.5",
  },
  {
    id: "HC37AE114",
    title: "Factory Authorized Parts™ - Blower Motor - 1/5 HP - RPM - 1075/3 SPD - 115 Volt - 2.9 A - 60 HZ - 1 PH",
    brand: "Factory Authorized Parts",
    item: "HC37AE114",
    mfg: "HC 37AE 114",
    price: 189.50,
    points: 189,
    stockStatus: "low-stock",
    allBranchesQty: 3,
    amps: "3",
    basisOfRotationView: "Lead End",
    bearingType: "Sleeve",
    capacitorMfdF: "5",
  },
  {
    id: "HC41AE117",
    title: "Factory Authorized Parts™ - Blower Motor - 1/3 HP - 115 V - 5.2 Amp - 1075 RPM",
    brand: "Factory Authorized Parts",
    item: "HC41AE117",
    mfg: "HC 41AE 117",
    price: 224.00,
    points: 224,
    stockStatus: "in-stock",
    allBranchesQty: 15,
    amps: "4",
    basisOfRotationView: "Lead End",
    bearingType: "Ball",
    capacitorMfdF: "5",
  },
  {
    id: "58MV660005",
    title: "Factory Authorized Parts™ - Blower Motor - 1 HP - 120/240 V - 12.8/7.4 Amp - 1300 RPM",
    brand: "Factory Authorized Parts",
    item: "58MV660005",
    mfg: "58MV 660 005",
    price: 489.25,
    points: 489,
    stockStatus: "in-stock",
    allBranchesQty: 6,
    amps: "15",
    basisOfRotationView: "Lead End",
    bearingType: "Ball",
    capacitorMfdF: "10",
  },
  {
    id: "HC45AE118",
    title: "Factory Authorized Parts™ - Blower Motor 3/4 HP 115 V 11.10 Amp 1075 RPM",
    brand: "Factory Authorized Parts",
    item: "HC45AE118",
    mfg: "HC 45AE 118",
    price: 371.90,
    points: 371,
    stockStatus: "in-stock",
    allBranchesQty: 9,
    amps: "15",
    basisOfRotationView: "Lead End",
    bearingType: "Ball",
    capacitorMfdF: "10",
  },
  {
    id: "HC43AQ116",
    title: "Factory Authorized Parts™ - Blower Motor",
    brand: "Factory Authorized Parts",
    item: "HC43AQ116",
    mfg: "HC 43AQ 116",
    price: 258.00,
    points: 258,
    stockStatus: "low-stock",
    allBranchesQty: 2,
    amps: "4",
    basisOfRotationView: "Shaft End",
    bearingType: "Ball",
    capacitorMfdF: "5",
  },
  {
    id: "HD46MQ133",
    title: "Factory Authorized Parts™ - Blower Motor - 3/4 HP (ECM) - 115/120V - 1050 RPM - CCW",
    brand: "Factory Authorized Parts",
    item: "HD46MQ133",
    mfg: "HD 46MQ 133",
    price: 512.75,
    points: 512,
    stockStatus: "in-stock",
    allBranchesQty: 4,
    amps: "7.7",
    basisOfRotationView: "Lead End",
    bearingType: "Ball",
    capacitorMfdF: "10",
  },
  {
    id: "HD56FE652",
    title: "Factory Authorized Parts™ - 2.4 HP Blower Motor - 208-230/460 V - 5.2/2.6 Amp - 1725 RPM",
    brand: "Factory Authorized Parts",
    item: "HD56FE652",
    mfg: "HD 56FE 652",
    price: 895.00,
    points: 895,
    stockStatus: "out-of-stock",
    allBranchesQty: 0,
    amps: "4",
    basisOfRotationView: "Drive End",
    bearingType: "Ball",
    capacitorMfdF: "15",
  },
  {
    id: "TP-EC13-50",
    title: "TRADEPRO® - Blower Motor - X-13 ECM - 1/2-1/3 HP - 115/208-230 V",
    brand: "TRADEPRO®",
    item: "TP-EC13-50",
    mfg: "TP-EC13-50",
    price: 265.00,
    points: 265,
    stockStatus: "in-stock",
    allBranchesQty: 22,
    amps: "4",
    basisOfRotationView: "Lead End",
    bearingType: "Ball",
    capacitorMfdF: "7.5",
  },
  {
    id: "TP-E50-3SP2",
    title: "TRADEPRO® - Blower Motor - 3-Speed - 1/2 HP - 115 V - 1075 RPM",
    brand: "TRADEPRO®",
    item: "TP-E50-3SP2",
    mfg: "TP-E50-3SP2",
    price: 158.50,
    points: 158,
    stockStatus: "in-stock",
    allBranchesQty: 18,
    amps: "7.7",
    basisOfRotationView: "Lead End",
    bearingType: "Sleeve",
    capacitorMfdF: "5",
  },
  {
    id: "TP-E75-2SP1",
    title: "TRADEPRO® - Blower Motor - 2-Speed - 3/4 HP - 115 V - 1075 RPM",
    brand: "TRADEPRO®",
    item: "TP-E75-2SP1",
    mfg: "TP-E75-2SP1",
    price: 192.00,
    points: 192,
    stockStatus: "in-stock",
    allBranchesQty: 11,
    amps: "15",
    basisOfRotationView: "Lead End",
    bearingType: "Sleeve",
    capacitorMfdF: "7.5",
  },
  {
    id: "US9656",
    title: "US MOTORS - Blower Motor - 1/2 HP - 208-230 V - 1075 RPM - 3-Speed",
    brand: "U.S. MOTORS",
    item: "9656",
    mfg: "9656",
    price: 214.75,
    points: 214,
    stockStatus: "in-stock",
    allBranchesQty: 7,
    amps: "4",
    basisOfRotationView: "Lead End",
    bearingType: "Ball",
    capacitorMfdF: "5",
  },
  {
    id: "GN-3S042",
    title: "Genteq® - PSC Blower Motor - 1/3 HP - 208-230 V - 1075 RPM - 3-Speed",
    brand: "Genteq®",
    item: "3S042",
    mfg: "3S042",
    price: 168.00,
    points: 168,
    stockStatus: "low-stock",
    allBranchesQty: 2,
    amps: "3",
    basisOfRotationView: "Lead End",
    bearingType: "Sleeve",
    capacitorMfdF: "5",
  },
  {
    id: "GN-5464",
    title: "Genteq® - ECM Blower Motor - 1/2 HP - 208-230 V - Programmable",
    brand: "Genteq®",
    item: "5464",
    mfg: "5464",
    price: 445.50,
    points: 445,
    stockStatus: "in-stock",
    allBranchesQty: 5,
    amps: "4",
    basisOfRotationView: "Lead End",
    bearingType: "Ball",
    capacitorMfdF: "10",
  },
  {
    id: "DT-M8907",
    title: "DiversiTech® - Universal Blower Motor - 1/4 HP - 115 V - 1075 RPM",
    brand: "DiversiTech®",
    item: "M8907",
    mfg: "M8907",
    price: 128.25,
    points: 128,
    stockStatus: "in-stock",
    allBranchesQty: 14,
    amps: "3",
    basisOfRotationView: "Lead End",
    bearingType: "Sleeve",
    capacitorMfdF: "5",
  },
  {
    id: "DT-M8908",
    title: "DiversiTech® - Universal Blower Motor - 1/3 HP - 115 V - 1075 RPM",
    brand: "DiversiTech®",
    item: "M8908",
    mfg: "M8908",
    price: 142.00,
    points: 142,
    stockStatus: "in-stock",
    allBranchesQty: 13,
    amps: "4",
    basisOfRotationView: "Lead End",
    bearingType: "Sleeve",
    capacitorMfdF: "5",
  },
  {
    id: "TL-BM12",
    title: "TOTALINE® - Direct Drive Blower Motor - 1/2 HP - 115 V - 1075 RPM",
    brand: "TOTALINE®",
    item: "BM12",
    mfg: "P262-BM12",
    price: 234.00,
    points: 234,
    stockStatus: "in-stock",
    allBranchesQty: 8,
    amps: "4",
    basisOfRotationView: "Drive End",
    bearingType: "Ball",
    capacitorMfdF: "7.5",
  },
  {
    id: "TL-BM34",
    title: "TOTALINE® - Direct Drive Blower Motor - 3/4 HP - 115 V - 1075 RPM",
    brand: "TOTALINE®",
    item: "BM34",
    mfg: "P262-BM34",
    price: 289.50,
    points: 289,
    stockStatus: "low-stock",
    allBranchesQty: 3,
    amps: "15",
    basisOfRotationView: "Drive End",
    bearingType: "Ball",
    capacitorMfdF: "10",
  },
  {
    id: "58MV660008",
    title: "Factory Authorized Parts™ - Blower Motor 1/4 HP - 120 V - 5.5 Amp - 1050 RPM",
    brand: "Factory Authorized Parts",
    item: "58MV660008",
    mfg: "58MV 660 008",
    price: 265.75,
    points: 265,
    stockStatus: "in-stock",
    allBranchesQty: 10,
    amps: "3",
    basisOfRotationView: "Lead End",
    bearingType: "Ball",
    capacitorMfdF: "5",
  },
  {
    id: "HC39GE237",
    title: "Factory Authorized Parts™ - Blower Motor 1/2 HP - 208-230 V - 3.2 Amp - 1075 RPM",
    brand: "Factory Authorized Parts",
    item: "HC39GE237",
    mfg: "HC 39GE 237",
    price: 356.00,
    points: 356,
    stockStatus: "in-stock",
    allBranchesQty: 6,
    amps: "0.53",
    basisOfRotationView: "Lead End",
    bearingType: "Sleeve",
    capacitorMfdF: "7.5",
  },
  {
    id: "HC44GE234",
    title: "Factory Authorized Parts™ - Blower Motor 3/4 HP - 208-230 V - 4.4 Amp - 1075 RPM",
    brand: "Factory Authorized Parts",
    item: "HC44GE234",
    mfg: "HC 44GE 234",
    price: 428.50,
    points: 428,
    stockStatus: "in-stock",
    allBranchesQty: 4,
    amps: "4",
    basisOfRotationView: "Lead End",
    bearingType: "Ball",
    capacitorMfdF: "10",
  },
  {
    id: "GN-3728",
    title: "Genteq® - ECM Blower Motor - 3/4 HP - 208-230 V - 1075 RPM Multi-Tap",
    brand: "Genteq®",
    item: "3728",
    mfg: "3728",
    price: 512.00,
    points: 512,
    stockStatus: "in-stock",
    allBranchesQty: 5,
    amps: "4",
    basisOfRotationView: "Lead End",
    bearingType: "Ball",
    capacitorMfdF: "10",
  },
  {
    id: "58MV660010",
    title: "Factory Authorized Parts™ - Blower Motor 1 HP - 208-230 V - 5.4 Amp - 1075 RPM",
    brand: "Factory Authorized Parts",
    item: "58MV660010",
    mfg: "58MV 660 010",
    price: 578.75,
    points: 578,
    stockStatus: "in-stock",
    allBranchesQty: 3,
    amps: "15",
    basisOfRotationView: "Lead End",
    bearingType: "Ball",
    capacitorMfdF: "15",
  },
];

/** Advertised as 101 on the source page — this is the "true" total behind the mock. */
export const TOTAL_RESULT_COUNT = 101;
