"use client";
import { useMemo, useState } from "react";
import { CheckCircle2, Filter, MoreHorizontal, Plus, Search, Settings2, Tag, Trash2 } from "lucide-react";
import { DashboardShell } from "../_components/dashboard-shell";

type ShoppingList = { name: string; label: string; products: number; type: "Personal" | "Shared"; activity: string; owner: string };
const LISTS: ShoppingList[] = [
  { name: "HVAC maintenance kit", label: "Preventative", products: 12, type: "Personal", activity: "Today", owner: "David Whiteside" },
  { name: "Blower motor replacements", label: "Job supplies", products: 4, type: "Personal", activity: "Yesterday", owner: "David Whiteside" },
  { name: "Frequently ordered parts", label: "", products: 18, type: "Shared", activity: "Aug 22, 2026", owner: "David Whiteside" },
];

export default function ShoppingListsPage() {
  const [query, setQuery] = useState(""); const [showMore, setShowMore] = useState(false); const [showCreate, setShowCreate] = useState(false); const [newName, setNewName] = useState(""); const [lists, setLists] = useState(LISTS);
  const filtered = useMemo(() => lists.filter((list) => list.name.toLowerCase().includes(query.toLowerCase())), [lists, query]);
  function createList() { const name = newName.trim(); if (!name) return; setLists((current) => [{ name, label: "", products: 0, type: "Personal", activity: "Just now", owner: "David Whiteside" }, ...current]); setNewName(""); setShowCreate(false); }
  return <DashboardShell title="Shopping lists" description="Save frequently ordered products for faster reordering and collaboration.">
    <section className="rounded-md border border-border bg-background shadow-sm">
      <div className="flex flex-col gap-4 border-b border-border p-5 md:flex-row md:items-start md:justify-between md:p-6"><div><h2 className="text-xl font-semibold">My shopping lists</h2><p className="mt-1 text-sm text-muted-foreground">Keep the parts you use most within easy reach.</p></div><button type="button" onClick={() => setShowCreate(true)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-md bg-primary px-4 text-sm font-semibold text-primary-foreground hover:bg-primary/90"><Plus className="size-4" aria-hidden="true" />Create list</button></div>
      <div className="flex flex-col gap-3 border-b border-border p-4 md:flex-row md:items-center"><label className="relative min-w-0 flex-1"><span className="sr-only">Search lists</span><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" aria-hidden="true" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search lists by name…" className="h-11 w-full rounded-md border border-border bg-background pl-10 pr-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" /></label><div className="flex flex-wrap gap-2"><button type="button" className="inline-flex h-11 items-center gap-2 rounded-md border border-border px-3 text-sm font-medium hover:bg-muted"><Filter className="size-4" aria-hidden="true" />Filter</button><button type="button" className="inline-flex h-11 items-center gap-2 rounded-md border border-border px-3 text-sm font-medium hover:bg-muted"><Tag className="size-4" aria-hidden="true" />Group by label</button><div className="relative"><button type="button" onClick={() => setShowMore((value) => !value)} aria-expanded={showMore} className="inline-flex h-11 items-center gap-2 rounded-md border border-border px-3 text-sm font-medium hover:bg-muted"><MoreHorizontal className="size-4" aria-hidden="true" />More</button>{showMore ? <div className="absolute right-0 z-10 mt-2 w-44 rounded-md border border-border bg-background p-1 text-sm shadow-lg"><button type="button" className="block w-full rounded px-3 py-2 text-left hover:bg-muted">Export lists</button><button type="button" className="block w-full rounded px-3 py-2 text-left hover:bg-muted">Manage labels</button></div> : null}</div></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><caption className="sr-only">Saved shopping lists</caption><thead className="bg-muted/40 text-xs font-semibold uppercase tracking-wide text-muted-foreground"><tr>{["Name", "Label", "Products", "Type", "Latest activity", "Created by", "Actions"].map((heading) => <th key={heading} scope="col" className="px-4 py-3">{heading}</th>)}</tr></thead><tbody className="divide-y divide-border">{filtered.map((list) => <tr key={list.name} className="hover:bg-muted/30"><th scope="row" className="px-4 py-4 font-semibold text-primary"><a href="#" className="hover:underline">{list.name}</a></th><td className="px-4 py-4">{list.label ? <span className="inline-flex items-center gap-1 text-muted-foreground"><Tag className="size-4" aria-hidden="true" />{list.label}</span> : <button type="button" className="text-primary hover:underline">Add label</button>}</td><td className="px-4 py-4">{list.products}</td><td className="px-4 py-4"><span className="rounded-full border border-border px-2.5 py-1 text-xs font-medium">{list.type}</span></td><td className="px-4 py-4 text-muted-foreground">{list.activity}</td><td className="px-4 py-4 text-muted-foreground">{list.owner}</td><td className="px-4 py-4"><div className="flex gap-1"><button type="button" aria-label={`Edit ${list.name}`} className="rounded p-2 text-muted-foreground hover:bg-muted hover:text-foreground"><Settings2 className="size-4" aria-hidden="true" /></button><button type="button" aria-label={`Delete ${list.name}`} className="rounded p-2 text-muted-foreground hover:bg-muted hover:text-destructive"><Trash2 className="size-4" aria-hidden="true" /></button></div></td></tr>)}</tbody></table>{!filtered.length ? <p className="p-10 text-center text-sm text-muted-foreground">No lists match your search.</p> : null}</div>
      <div className="flex items-center gap-2 border-t border-border px-4 py-4 text-sm text-muted-foreground"><CheckCircle2 className="size-4" aria-hidden="true" />{filtered.length} {filtered.length === 1 ? "list" : "lists"} shown</div>
    </section>
    {showCreate ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setShowCreate(false); }}><div role="dialog" aria-modal="true" aria-labelledby="create-list-title" className="w-full max-w-md rounded-md border border-border bg-background p-6 shadow-xl"><h2 id="create-list-title" className="text-xl font-semibold">Create a shopping list</h2><label className="mt-5 block text-sm font-medium">List name<input autoFocus value={newName} onChange={(event) => setNewName(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") createList(); }} className="mt-2 h-11 w-full rounded-md border border-border px-3 outline-none focus-visible:ring-2 focus-visible:ring-ring" placeholder="e.g. Summer maintenance" /></label><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setShowCreate(false)} className="min-h-11 rounded-md border border-border px-4 text-sm font-semibold hover:bg-muted">Cancel</button><button type="button" onClick={createList} className="min-h-11 rounded-md bg-primary px-4 text-sm font-semibold text-primary-foreground hover:bg-primary/90">Create list</button></div></div></div> : null}
  </DashboardShell>;
}
